version: '3.7'

services:
  gatsby:
    container_name: gatsby
    init: true
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: ./docker/entrypoint.sh develop
    volumes:
      - .:/app:${CONSISTENCY:-cached}
      - ./node_modules/:/app/node_modules:${CONSISTENCY:-cached}
    ports:
      - 8000:8000
