version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public/
            - firebase.json
      - run: echo "Sound! Euphonium"
  deploy_production:
    docker:
      - image: circleci/node:8.12.0-stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn global add firebase-tools
      - run:
          name: Deploy to Firebase
          command: $(yarn global bin)/firebase deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
