version: 2
default_settings: &default_settings
  docker:
    - image: circleci/node:16.11.1-stretch
  working_directory: ~/repo
jobs:
  build:
    <<: *default_settings
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public/
            - firebase.json
      - run: echo "Sound! Euphonium"
  deploy_production:
    <<: *default_settings
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn global add firebase-tools
      - run:
          name: Deploy to Firebase
          command: $(yarn global bin)/firebase deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
