version: 2
jobs:
  build:
    working_directory: ~/gatsby-firebase
    docker:
      - image: node:8.12.0-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies for Gatsby
          command: |
            apk add --no-cache --virtual .gyp python gcc g++ make
            apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
            vips-tools vips-dev fftw-dev libc6-compat
            rm -rf /var/cache/apk/*
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: echo "Sound! Euphonium"


